theme: jekyll-theme-minimal
logo: /portraitMINI.jpg
title: Leandra Bräuninger
description: "Please don't hesitate to reach out to me if our research interests overlap, if your startup is looking for a research collaborator or scientific advisor or if you are looking for someone to teach or present on the topics of Health x AI x Ethics.
<br> 
leandra.braeuninger@gmail.com"
show_downloads: false
