theme: jekyll-theme-minimal
logo: /portraitMINI.jpg
title: Leandra Bräuninger
description: "Doctoral Student @ UCL Stats
<br>
AI x Health x Equity
<br> 
leandra.braeuninger@gmail.com"
show_downloads: false
github: none
