theme: jekyll-theme-minimal
logo: /portraitMINI.jpg
title: Leandra Bräuninger
description: "Doctoral Student @ UCL Stats
<br>
AI x Health x Equity
<br> 
<br>
Please don't hesitate to reach out to me if our research interests overlap, if your startup is looking for a research collaborator or scientific advisor or if you are looking for someone to teach or present on equitable HealthTech.
<br> 
<br>
leandra.braeuninger@gmail.com"
show_downloads: false
github: none
