theme: jekyll-theme-minimal
logo: /portrait25.png
title: Leandra Bräuninger
description: "<strong>Looking for post-PhD academic positions!</strong>
<br>
Doctoral Researcher @ UCL Stats
<br>
AI x Health x Equity
<br> 
leandra.braeuninger@gmail.com"
show_downloads: false
github: none
