theme: jekyll-theme-minimal
logo: /portraitMINI.jpg
title: Leandra Bräuninger
description: Please don't hesitate to reach out to me if our research interests overlap, if your startup is looking for a research collaborator or scientific advisor or if you are looking for someone to teach or present on the topics of Health x AI x Ethics.

Email: leandra.braeuninger@gmail.com

Linkedin: [linkedin.com/in/leandra-braeuninger/](https://www.linkedin.com/in/leandra-braeuninger/)

Twitter: [@_LeandraBr](https://twitter.com/_LeandraBr)
